#%RAML 0.8
title: User import
version: v1
baseUri: https://github.com/folio-org/mod-user-import

documentation:
  - title: mod-user-import API
    content: This documents the API calls that can be made to import users into the system

schemas:
  - userdataimport.json: !include schemas/userdataimport.json
  - userdataimportCollection: !include schemas/userdataimportCollection.json
  - failedUserdata.json: !include schemas/failedUserdata.json
  - importResponse: !include schemas/importResponse.json
  - metadata.schema: !include schemas/metadata.schema
  - tags.schema: !include schemas/tags.schema

/user-import:
  get:
    responses:
      400:
        description: "Fake endpoint"
        body:
          text/plain:
  post:
    body:
      application/json:
        schema: userdataimportCollection
    description: Create or update a list of users
    responses:
      200:
        description: "Return OK"
        body:
          application/json:
            schema: importResponse
      500:
        description: "Internal server error"
        body:
          application/json:
            schema: importResponse
