#%RAML 0.8
title: User import
version: v1
baseUri: http://github.com/org/qultoltd/mod-user-import

documentation:
  - title: mod-user-import API
    content: This documents the API calls that can be made to import users into the system

schemas:
  - userdata: !include schemas/userdata.json
  - userdataCollection: !include schemas/userdataCollection.json

/user-import:
  get:
    responses:
      200:
        description: "Fake endpoint"
        body:
          text/plain:
  post:
    body:
      application/json:
        schema: userdataCollection
    description: Create or update a list of users
    responses:
      200:
        description: "Return OK"
        body:
          text/plain:
      400:
        description: "Bad request, possibly error in user data"
        body:
          text/plain:
      500:
        description: "Internal server error"
        body:
          text/plain:
